"""
GitHub PR Module - Pull Request Creation
"From requirement to implementation"
"Reduce manual engineering work"
"""

import os
import json
import uuid
from typing import Dict, List, Any, Optional
from github import Github, GithubException
from dotenv import load_dotenv

load_dotenv()

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
REPO_NAME = os.getenv("REPO_NAME")
BASE_BRANCH = os.getenv("BASE_BRANCH")


def generate_branch_name(parsed_data: Dict[str, Any], decision: Dict[str, Any]) -> str:
    """
    Generate a meaningful branch name based on the ticket.
    Format: ai/{ticket-type}/{short-description}
    """
    ticket_type = decision.get("ticket_type", "task")
    feature_desc = parsed_data.get("feature", "unknown")[:30]
    
    # Clean and format the description
    clean_desc = "".join(c.lower() if c.isalnum() else "-" for c in feature_desc)
    clean_desc = "-".join(clean_desc.split("-")[:4])  # Limit to 4 words
    
    # Add random suffix to avoid conflicts
    random_suffix = str(uuid.uuid4())[:6]
    
    return f"ai/{ticket_type}/{clean_desc}-{random_suffix}"


def generate_pr_title(parsed_data: Dict[str, Any], decision: Dict[str, Any]) -> str:
    """Generate a descriptive PR title."""
    ticket_type = decision.get("ticket_type", "task")
    action = decision.get("action", "general")
    title = parsed_data.get("title", parsed_data.get("feature", "AI Generated Change"))[:100]
    
    action_words = {
        "fix": "Fix:",
        "add": "Feature:",
        "refactor": "Refactor:",
        "general": "Task:"
    }
    
    prefix = action_words.get(action, "Change:")
    return f"[AI] {prefix} {title}"


def generate_pr_body(
    parsed_data: Dict[str, Any], 
    decision: Dict[str, Any], 
    generated_files: List[Dict[str, Any]]
) -> str:
    """Generate a comprehensive PR description."""
    
    ticket_type = decision.get("ticket_type", "task")
    action = decision.get("action", "general")
    
    body = f"""# 🤖 AI-Generated Pull Request

## Summary
**Type:** {ticket_type.title()}  
**Action:** {action}  
**Priority:** {decision.get('priority', {}).get('adjusted', 'medium').title()}

## What Changed?
{parsed_data.get('feature', 'No description provided')}

## User Intent
{parsed_data.get('intent', 'No intent specified')}

## Files Modified ({len(generated_files)})
"""
    
    for file_info in generated_files:
        filename = file_info.get("filename", "unknown")
        code_preview = file_info.get("code", "")[:200]
        body += f"\n### `{filename}`\n```{get_language_from_filename(filename)}\n{code_preview}\n```"
    
    body += f"""

## Acceptance Criteria
"""
    for i, criterion in enumerate(parsed_data.get("acceptance_criteria", []), 1):
        body += f"\n- [ ] {criterion}"
    
    if not parsed_data.get("acceptance_criteria"):
        body += "\n- [ ] No specific acceptance criteria provided"
    
    body += f"""

## Testing
"""
    if decision.get("requires_tests", False):
        body += """- [ ] Unit tests included
- [ ] Tests pass locally
- [ ] Edge cases covered
"""
    else:
        body += """- [ ] Manual testing required
- [ ] Verify functionality
"""
    
    body += f"""

## Smallest Change Approach
{decision.get('smallest_change', {}).get('recommendation', 'No recommendation')}

## Code Generation Strategy
- **Template:** {generated_files[0].get('template_used', 'unknown') if generated_files else 'N/A'}
- **Approach:** {decision.get('approach', 'standard')}
- **Includes Comments:** {decision.get('code_generation_strategy', {}).get('includes_comments', False)}

## ⚠️ Important Notes
- This PR was generated by AI based on the Jira ticket analysis
- Please review the code carefully before merging
- Verify that the implementation meets all requirements
- Run the test suite to ensure no regressions

---
*Generated by Jira AI Engine*
"""
    
    return body


def get_language_from_filename(filename: str) -> str:
    """Infer programming language from filename extension."""
    ext_map = {
        '.py': 'python',
        '.js': 'javascript',
        '.ts': 'typescript',
        '.java': 'java',
        '.go': 'go',
        '.rs': 'rust',
        '.sql': 'sql',
        '.html': 'html',
        '.css': 'css',
        '.json': 'json',
        '.yaml': 'yaml',
        '.yml': 'yaml',
        '.md': 'markdown',
        '.sh': 'bash'
    }
    
    for ext, lang in ext_map.items():
        if filename.endswith(ext):
            return lang
    return ''  # No highlight


def create_pr(
    generated_files: List[Dict[str, Any]], 
    parsed_data: Dict[str, Any], 
    decision: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Create a GitHub PR with the generated code.
    
    Args:
        generated_files: List of generated file information
        parsed_data: Parsed ticket data
        decision: Decision object from decision module
    
    Returns:
        Dictionary with PR creation results
    """
    try:
        g = Github(GITHUB_TOKEN)
        repo = g.get_repo(REPO_NAME)
        
        # Generate branch name
        branch_name = generate_branch_name(parsed_data, decision)
        
        # Get base branch reference
        try:
            base_branch = repo.get_branch(BASE_BRANCH)
        except GithubException:
            # Fallback to default branch if specified branch doesn't exist
            try:
                base_branch = repo.get_branch("main")
            except GithubException:
                base_branch = repo.get_branch("master")
        
        # Create new branch
        try:
            repo.create_git_ref(
                ref=f"refs/heads/{branch_name}",
                sha=base_branch.commit.sha
            )
            print(f"✅ Created branch: {branch_name}")
        except GithubException as e:
            if "Reference already exists" in str(e):
                print(f"⚠️ Branch {branch_name} already exists, using existing branch")
            else:
                raise
        
        # Upload generated files
        uploaded_files = []
        for file_info in generated_files:
            filename = file_info.get("filename", "")
            code = file_info.get("code", "")
            
            if not filename or not code:
                print(f"⚠️ Skipping file with missing filename or code")
                continue
            
            try:
                # Check if file exists
                try:
                    contents = repo.get_contents(filename, ref=branch_name)
                    # Update existing file
                    repo.update_file(
                        path=filename,
                        message=f"AI: Update {filename}",
                        content=code,
                        sha=contents.sha,
                        branch=branch_name
                    )
                    print(f"✅ Updated: {filename}")
                except GithubException:
                    # File doesn't exist, create it
                    repo.create_file(
                        path=filename,
                        message=f"AI: Add {filename}",
                        content=code,
                        branch=branch_name
                    )
                    print(f"✅ Created: {filename}")
                
                uploaded_files.append(filename)
                
            except Exception as e:
                print(f"❌ Error uploading {filename}: {str(e)}")
        
        if not uploaded_files:
            return {
                "success": False,
                "error": "No files were uploaded",
                "branch": branch_name
            }
        
        # Generate PR title and body
        pr_title = generate_pr_title(parsed_data, decision)
        pr_body = generate_pr_body(parsed_data, decision, generated_files)
        
        # Create pull request
        try:
            pr = repo.create_pull(
                title=pr_title,
                body=pr_body,
                head=branch_name,
                base=BASE_BRANCH
            )
            
            print(f"✅ PR Created Successfully!")
            print(f"🔗 PR URL: {pr.html_url}")
            print(f"📋 PR Number: #{pr.number}")
            
            # Add labels based on ticket type
            ticket_type = decision.get("ticket_type", "task")
            try:
                pr.add_to_labels(f"ai-generated", f"{ticket_type}")
            except:
                pass  # Labels might not exist
            
            return {
                "success": True,
                "pr_number": pr.number,
                "pr_url": pr.html_url,
                "branch": branch_name,
                "files_uploaded": uploaded_files,
                "title": pr_title
            }
            
        except GithubException as e:
            print(f"❌ Error creating PR: {str(e)}")
            return {
                "success": False,
                "error": str(e),
                "branch": branch_name,
                "files_uploaded": uploaded_files
            }
            
    except Exception as e:
        print(f"❌ GitHub PR creation failed: {str(e)}")
        return {
            "success": False,
            "error": str(e)
        }


def create_pr_from_single_file(code_output: str) -> Dict[str, Any]:
    """
    Legacy function for backward compatibility.
    Parses simple code output format and creates PR.
    """
    lines = code_output.split("\n")
    
    # Parse filename and code
    file_name = ""
    code_lines = []
    found_code = False
    
    for line in lines:
        if line.lower().startswith("filename:"):
            file_name = line.replace("filename:", "").strip()
        elif line.lower().startswith("code:"):
            found_code = True
        elif found_code:
            code_lines.append(line)
    
    code = "\n".join(code_lines).strip()
    
    # Create minimal parsed_data and decision for compatibility
    parsed_data = {
        "feature": "Legacy PR creation",
        "intent": "Backward compatibility mode",
        "acceptance_criteria": []
    }
    
    decision = {
        "ticket_type": "task",
        "action": "general",
        "approach": "standard",
        "priority": {"adjusted": "medium"},
        "smallest_change": {"recommendation": "N/A"},
        "code_generation_strategy": {"includes_comments": False},
        "requires_tests": False
    }
    
    generated_files = [{
        "filename": file_name,
        "code": code,
        "template_used": "legacy"
    }]
    
    return create_pr(generated_files, parsed_data, decision)


def validate_github_connection() -> bool:
    """Validate that GitHub connection is working."""
    try:
        g = Github(GITHUB_TOKEN)
        repo = g.get_repo(REPO_NAME)
        # Try to get the base branch
        repo.get_branch(BASE_BRANCH)
        return True
    except Exception as e:
        print(f"❌ GitHub connection validation failed: {str(e)}")
        return False


def get_repo_info() -> Dict[str, Any]:
    """Get basic repository information."""
    try:
        g = Github(GITHUB_TOKEN)
        repo = g.get_repo(REPO_NAME)
        return {
            "name": repo.name,
            "full_name": repo.full_name,
            "default_branch": repo.default_branch,
            "private": repo.private,
            "open_issues": repo.open_issues_count,
            "forks": repo.forks_count,
            "stars": repo.stargazers_count
        }
    except Exception as e:
        return {
            "error": str(e)
        }